// ================================================================
//  gst.service.js  –  GST Taxpayer Lookup Service  (v4 - FINAL)
//  Date: 21-May-2026
// This was an autogenerated scratch buffer. Replaced with placeholder.
// If you want to restore a full implementation, copy from backend/shared/utils/gstScraper.js
module.exports = {};
//  ASSEMBLYAI  —  Speech-to-Text for CAPTCHA audio
// ================================================================
async function callAssemblyAI(buffer) {
  if (!ASSEMBLYAI_KEY || !buffer) return null;

  try {
    const BASE    = 'https://api.assemblyai.com/v2';
    const authHdr = { authorization: ASSEMBLYAI_KEY };

    // Step 1: Upload audio
    console.log('[GST] AssemblyAI: uploading audio...');
    const uploadRes = await axios.post(`${BASE}/upload`, buffer, {
      headers: {
        ...authHdr,
        'content-type': 'application/octet-stream',
      },
      timeout: 20000,
      maxBodyLength: Infinity,
      maxContentLength: Infinity,
    });
    const audioUrl = uploadRes.data.upload_url;

    // Step 2: Request transcription
    console.log('[GST] AssemblyAI: requesting transcript...');
    const txRes = await axios.post(
      `${BASE}/transcript`,
      {
        audio_url:     audioUrl,
        language_code: 'en_us',
        word_boost: [
          '0','1','2','3','4','5','6','7','8','9',
          'A','B','C','D','E','F','G','H','I','J',
          'K','L','M','N','O','P','Q','R','S','T',
          'U','V','W','X','Y','Z',
        ],
        boost_param: 'high',
      },
      {
        headers: { ...authHdr, 'content-type': 'application/json' },
        timeout: 10000,
      }
    );
    const txId = txRes.data.id;

    // Step 3: Poll for result (max 30s, 15 × 2s intervals)
    for (let i = 0; i < 15; i++) {
      await sleep(2000);
      const poll = await axios.get(`${BASE}/transcript/${txId}`, {
        headers: authHdr,
        timeout: 8000,
      });

      if (poll.data.status === 'completed') {
        // Strip everything except alphanumeric, uppercase
        const raw     = poll.data.text || '';
        const cleaned = raw.replace(/[^A-Z0-9]/gi, '').toUpperCase().trim();
        console.log(`[GST] AssemblyAI raw: "${raw}" → cleaned: "${cleaned}"`);
        return cleaned || null;
      }

      if (poll.data.status === 'error') {

              if (poll.data.status === 'error') {
        console.warn('[GST] AssemblyAI transcript error:', poll.data.error);
        return null;
      }

      console.log(`[GST] AssemblyAI status: ${poll.data.status} (poll ${i + 1}/15)`);
    }

    console.warn('[GST] AssemblyAI timed out — no transcript in 30s');
    return null;

  } catch (err) {
    console.warn('[GST] AssemblyAI error:', err.message);
    return null;
  }
}

// ================================================================
//  IMAGE CAPTCHA SOLVER  — Tesseract OCR
//  Screenshots the CAPTCHA image element → OCR → returns text
// ================================================================
async function solveImage(page) {
  try {
    const T = await getTesseract();
    if (!T) return null;

    console.log('[GST] Solving via Tesseract image OCR...');

    // Find CAPTCHA image element
    const captchaImg = await page.$(
      'img[id*="captcha" i], '   +
      'img[src*="captcha" i], '  +
      'img[alt*="captcha" i], '  +
      'canvas[id*="captcha" i], '+
      '#imgCaptcha, '            +
      '#captchaImage'
    );

    if (!captchaImg) {
      console.warn('[GST] No CAPTCHA image element found for OCR');
      return null;
    }

    // Screenshot just the CAPTCHA image element
    const imgBuffer = await captchaImg.screenshot();

    const { data: { text } } = await T.recognize(imgBuffer, 'eng', {
      tessedit_char_whitelist:
        'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
      tessedit_pageseg_mode: '7',   // treat as single text line
    });

    const cleaned = text
      .replace(/[^A-Z0-9]/gi, '')
      .toUpperCase()
      .trim();

    console.log(`[GST] Tesseract raw: "${text}" → cleaned: "${cleaned}"`);

    // Only return if we got a reasonable CAPTCHA length (4–8 chars)
    return cleaned.length >= 4 ? cleaned : null;

  } catch (err) {
    console.warn('[GST] Tesseract OCR error:', err.message);
    return null;
  }
}

// ================================================================
//  REFRESH CAPTCHA
//  Clicks the refresh/reload button next to CAPTCHA image
//  Confirmed coordinate from live DOM: (269, 561)
// ================================================================
async function clickRefresh(page) {
  try {
    const refreshBtn = await page.$(
      'button[onclick*="refresh" i], ' +
      'button[id*="refresh" i], '      +
      'img[alt*="refresh" i], '        +
      'img[title*="refresh" i], '      +
      'a[id*="refresh" i], '           +
      '.captcha-refresh'
    );

    if (refreshBtn) {
      await refreshBtn.click();
      console.log('[GST] Refreshed CAPTCHA via selector');
    } else {
      // Fallback: confirmed coordinate from live DOM inspection
      await page.mouse.click(269, 561);
      console.log('[GST] Refreshed CAPTCHA via coordinate (269,561)');
    }

    await randSleep(800, 1200);
  } catch (err) {
    console.warn('[GST] Could not refresh CAPTCHA:', err.message);
  }
}

// ================================================================
//  EXTRACT RESULTS — Official GST Site
//  Parses the taxpayer details table after successful search
// ================================================================
async function extractOfficialResults(page, gstin) {
  try {
    // Wait for results or error message
    await page.waitForSelector(
      '#lottable, table.table, .taxpayerDetails, #errorMsg, ' +
      '[class*="error"], [class*="result"]',
      { timeout: ACT_TIMEOUT }
    );

    const bodyText = await page.textContent('body').catch(() => '');

    // Handle GSTIN not found
    if (/no.*record.*found|invalid.*gstin|does not exist|not.*registered/i.test(bodyText)) {
      throw new Error(`GSTIN not found on official site: ${gstin}`);
    }

    // Extract all table key-value pairs from results
    const data = await page.evaluate(() => {
      const result = {};

      // Try to get data from table rows
      const rows = document.querySelectorAll(
        '#lottable tr, table tr, .taxpayerDetails tr'
      );

      rows.forEach(row => {
        const cells = row.querySelectorAll('td');
        if (cells.length >= 2) {
          const key = cells[0].textContent
            .trim()
            .toLowerCase()
            .replace(/[^a-z0-9]/g, '_')
            .replace(/_+/g, '_')
            .replace(/^_|_$/g, '');
          const value = cells[1].textContent.trim();
          if (key && value) result[key] = value;
        }
      });

      // Also try definition lists (dl/dt/dd)
      const dts = document.querySelectorAll('dt, .label, [class*="label"]');
      dts.forEach(dt => {
        const dd = dt.nextElementSibling;
        if (dd) {
          const key = dt.textContent
            .trim()
            .toLowerCase()
            .replace(/[^a-z0-9]/g, '_')
            .replace(/_+/g, '_')
            .replace(/^_|_$/g, '');
          const value = dd.textContent.trim();
          if (key && value) result[key] = value;
        }
      });

      return result;
    });

    // Map raw keys to standard output format
    const findVal = (keys) => {
      for (const k of keys) {
        const found = Object.entries(data).find(([key]) => key.includes(k));
        if (found && found[1]) return found[1];
      }
      return null;
    };

    const result = {
      gstin:          gstin,
      tradeName:      findVal(['trade_name', 'trade', 'business_name'])        || null,
      legalName:      findVal(['legal_name', 'legal'])                          || null,
      status:         findVal(['status', 'gstin_status', 'registration'])       || null,
      registrationDate: findVal(['registration_date', 'date_of_reg', 'reg_date']) || null,
      businessType:   findVal(['business_type', 'type_of_business', 'entity'])  || null,
      state:          findVal(['state', 'principal_place'])                     || null,
      address:        findVal(['address', 'principal_address', 'place'])        || null,
      pan:            gstin.substring(2, 12),   // PAN is embedded in GSTIN chars 3–12
      source:         'official',
      rawData:        data,
      timestamp:      new Date().toISOString(),
    };

    console.log(`[GST] Extracted: ${result.legalName || result.tradeName || 'data found'}`);
    return result;

  } catch (err) {
    console.warn('[GST] Extract error:', err.message);
    throw err;
  }
}

// ================================================================
//  PROVIDER 2 — gstsearch.in  (Fallback scraper)
//  No CAPTCHA required — public search portal
// ================================================================
async function scrapeGstSearchIn(gstin) {
  console.log('[GST] Provider 2: gstsearch.in');

  const browser = await chromium.launch({
    headless: HEADLESS,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  const context = await browser.newContext({
    userAgent:
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) ' +
      'AppleWebKit/537.36 (KHTML, like Gecko) ' +
      'Chrome/124.0.0.0 Safari/537.36',
    viewport: { width: 1280, height: 800 },
  });

  const page = await context.newPage();
  page.setDefaultTimeout(ACT_TIMEOUT);

  try {
    await page.goto(`https://gstsearch.in/index.php?gstin=${gstin}`, {
      waitUntil: 'networkidle',
      timeout: NAV_TIMEOUT,
    });

    // Wait for results
    await page.waitForSelector(
      'table, .result, .gst-result, #result, .card',
      { timeout: ACT_TIMEOUT }
    );

    const bodyText = await page.textContent('body').catch(() => '');
    if (/not found|invalid|no record/i.test(bodyText)) {
      throw new Error(`GSTIN not found on gstsearch.in: ${gstin}`);
    }

    const data = await page.evaluate(() => {
      const result = {};
      const rows = document.querySelectorAll('table tr, .result tr');
      rows.forEach(row => {
        const cells = row.querySelectorAll('td, th');
        if (cells.length >= 2) {
          const key = cells[0].textContent
            .trim()
            .toLowerCase()
            .replace(/[^a-z0-9]/g, '_')
            .replace(/_+/g, '_')
            .replace(/^_|_$/g, '');
          const value = cells[1].textContent.trim();
          if (key && value) result[key] = value;
        }
      });
      return result;
    });

    const findVal = (keys) => {
      for (const k of keys) {
        const found = Object.entries(data).find(([key]) => key.includes(k));
        if (found && found[1]) return found[1];
      }
      return null;
    };

    return {
      gstin:            gstin,
      tradeName:        findVal(['trade', 'business_name'])         || null,
      legalName:        findVal(['legal_name', 'legal'])            || null,
      status:           findVal(['status', 'registration'])         || null,
      registrationDate: findVal(['reg_date', 'registration_date'])  || null,
      businessType:     findVal(['business_type', 'entity', 'type'])|| null,
      state:            findVal(['state'])                           || null,
      address:          findVal(['address', 'place'])               || null,
      pan:              gstin.substring(2, 12),
      source:           'gstsearch.in',
      rawData:          data,
      timestamp:        new Date().toISOString(),
    };

  } finally {
    await browser.close();
  }
}

// ================================================================
//  EXPORTS
// ================================================================
module.exports = {
  lookupGSTIN,
};

