export const THEME = {
  colors: {
    background: 'var(--bg-primary)',
    surface: 'var(--surface-raised)',
    surfaceSoft: 'var(--surface-subtle)',
    frost: 'var(--surface-subtle)',
    text: 'var(--text-primary)',
    textSecondary: 'var(--text-secondary)',
    textMuted: 'var(--text-muted)',
    border: 'var(--border-color)',
    accent: 'var(--color-primary)',
    accentSoft: 'var(--accent-soft)',
    success: 'var(--color-success)',
    error: 'var(--color-danger)',
    warning: 'var(--color-warning)',
    info: 'var(--color-info)',
    surfaceAlt: 'var(--surface-muted)',
    surfaceBorder: 'var(--surface-border)',
  },
  radius: {
    card: '24px',
    input: '16px',
    button: '16px',
    modal: '28px',
  },
  shadow: {
    soft: '0 16px 40px rgba(15, 23, 42, 0.08)',
    card: '0 24px 60px rgba(15, 23, 42, 0.08)',
    subtle: '0 8px 24px rgba(15, 23, 42, 0.06)',
  },
  plan: {
    free: { accent: 'var(--color-success)', label: 'Basic / Free', badgeBg: 'var(--success-soft)', border: 'var(--color-success)' },
    trial: { accent: 'var(--color-success)', label: '14-Day Trial', badgeBg: 'var(--success-soft)', border: 'var(--color-success)' },
    custom: { accent: 'var(--color-primary)', label: 'Custom / Add-on', badgeBg: 'var(--accent-soft)', border: 'var(--color-primary)' },
    pro: { accent: 'var(--color-primary)', label: 'Pro', badgeBg: 'var(--accent-soft)', border: 'var(--color-primary)' },
  },
  toast: {
    success: { background: 'var(--success-soft)', border: '1px solid var(--color-success)', color: 'var(--color-success)' },
    error: { background: 'var(--danger-soft)', border: '1px solid var(--color-danger)', color: 'var(--color-danger)' },
  },
};
